# Generated by Django 3.2.7 on 2021-10-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_name', models.CharField(db_column='T_name', max_length=100)),
                ('T_type', models.TextField()),
                ('T_vtg', models.IntegerField()),
            ],
            options={
                'db_table': 'transformer',
            },
        ),
    ]
